import json
from openpyxl import Workbook
from openpyxl.comments import Comment
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter


def export_mcp_report(test_cases, results, overall_stats=None, thresholds=None, output_file="MCP_Test_Report.xlsx"):

    thresholds = thresholds or {}   # safe default if called without per-metric thresholds

    # ── Build detail rows: one row per golden query ────────────────────────────
    detail_data = []
    for i, tc in enumerate(test_cases):
        row = {
            "Query":           tc.input,
            "Expected Output": tc.expected_output,
            "Actual Output":   tc.actual_output,
        }
        for metric_name, scores in results.items():
            row[metric_name] = round(scores[i], 3) if scores[i] is not None else "N/A"
        detail_data.append(row)

    # ── Build summary rows: one row per metric ──────────────────────────────────
    # Now also computes a per-metric Pass Rate (how many individual test cases
    # cleared that metric's threshold) and Total (how many test cases had a
    # valid score for that metric), alongside the existing Average Score.
    summary_data = []
    for metric_name, scores in results.items():
        valid_scores   = [s for s in scores if s is not None]
        avg            = sum(valid_scores) / len(valid_scores) if valid_scores else 0
        metric_threshold = thresholds.get(metric_name, 0.7)

        total  = len(valid_scores)
        passed = sum(1 for s in valid_scores if s >= metric_threshold)
        failed = total - passed
        pass_rate = (passed / total * 100) if total else 0

        summary_data.append({
            "Metric":        metric_name,
            "Average Score": round(avg, 3),
            "Pass Rate":     f"{pass_rate:.2f}%  ({passed}/{total})",
            "Total":         total,
        })

    # ── Style constants ─────────────────────────────────────────────────────────
    wb = Workbook()
    wb.remove(wb.active)

    HEADER_COLOR     = "2F4F7F"   # dark blue
    PASS_COLOR       = "C6EFCE"
    FAIL_COLOR       = "FFC7CE"
    PASS_FONT_COLOR  = "276221"
    FAIL_FONT_COLOR  = "9C0006"
    SCORE_HIGH_COLOR = "E2EFDA"   # pass green (used for all metrics when above threshold)
    SCORE_LOW_COLOR  = "FFEB9C"   # generic fail yellow (used for hard/strict metrics, e.g. tool correctness)
    COSINE_LOW_COLOR = "F2F9EE"   # distinct lighter green for Cosine_Similarity fails — softer since it's a graded/semantic metric, not a strict pass/fail one

    # Name of the metric that should use COSINE_LOW_COLOR instead of SCORE_LOW_COLOR when failing.
    COSINE_METRIC_NAME = "Cosine_Similarity"

    def mk_font(bold=False, color="000000", size=10, italic=False):
        return Font(name="Arial", bold=bold, color=color, size=size, italic=italic)

    def mk_fill(color):
        return PatternFill("solid", start_color=color)

    def fail_color_for(metric_name):
        """Returns the appropriate 'below threshold' fill color for a given metric."""
        return COSINE_LOW_COLOR if metric_name == COSINE_METRIC_NAME else SCORE_LOW_COLOR

    center = Alignment(horizontal="center", vertical="center", wrap_text=True)
    left   = Alignment(horizontal="left",   vertical="center", wrap_text=True)

    thin = Side(style="thin", color="CCCCCC")

    def thin_border():
        return Border(left=thin, right=thin, top=thin, bottom=thin)

    header_comments = {
        "Query":                              "The natural language question sent to the MCP agent.",
        "Expected Output":                    "The ideal/golden answer for the query.",
        "Actual Output":                      "The answer generated by the LLM after calling MCP tools.",
        "MCP_Use":                            "Checks tool args and whether results were used correctly in the final answer.",
        "Tool_Correctness(Tool-Exact-Match)": "Checks whether exactly the right set of tools was called (no extra, none missed).",
        "Tool_Correctness(Tool-Ordering)":    "Checks whether tools were called in the correct order.",
        "Cosine_Similarity":                  "Real embedding cosine similarity between expected and actual output.",
    }

    # ══════════════════════════════════════════════════════════════════════════
    # SHEET 1 — Detailed Report
    # ══════════════════════════════════════════════════════════════════════════
    ws = wb.create_sheet("Detailed Report")

    headers            = ["Query", "Expected Output", "Actual Output"] + list(results.keys())
    left_align_headers  = {"Query", "Expected Output", "Actual Output"}
    score_headers       = set(results.keys())
    col_widths          = [25, 35, 35] + [22] * len(results)
    n_cols              = len(headers)

    banner = ws.cell(row=1, column=1, value="MCP EVALUATION REPORT")
    ws.merge_cells(start_row=1, start_column=1, end_row=1, end_column=n_cols)
    banner.font      = mk_font(bold=True, color="FFFFFF", size=13)
    banner.fill      = mk_fill(HEADER_COLOR)
    banner.alignment = center
    banner.border    = thin_border()
    ws.row_dimensions[1].height = 28

    for i, h in enumerate(headers):
        col            = i + 1
        cell           = ws.cell(row=2, column=col, value=h)
        cell.font      = mk_font(bold=True, color="FFFFFF", size=11)
        cell.fill      = mk_fill(HEADER_COLOR)
        cell.alignment = center
        cell.border    = thin_border()
        if h in header_comments:
            cmt        = Comment(header_comments[h], "MCP Evaluator")
            cmt.width  = 300
            cmt.height = 60
            cell.comment = cmt
    ws.row_dimensions[2].height = 30

    for r_idx, row in enumerate(detail_data):
        excel_row = r_idx + 3
        for i, h in enumerate(headers):
            col            = i + 1
            val            = row.get(h, "")
            cell           = ws.cell(row=excel_row, column=col, value=val)
            cell.border    = thin_border()
            cell.font      = mk_font()
            cell.alignment = left if h in left_align_headers else center
            if h in score_headers and val not in (None, "", "N/A"):
                try:
                    cell_threshold = thresholds.get(h, 0.7)
                    if float(val) >= cell_threshold:
                        cell.fill = mk_fill(SCORE_HIGH_COLOR)
                    else:
                        cell.fill = mk_fill(fail_color_for(h))
                except (ValueError, TypeError):
                    pass
        ws.row_dimensions[excel_row].height = 100

    for i, w in enumerate(col_widths):
        ws.column_dimensions[get_column_letter(i + 1)].width = w
    # ══════════════════════════════════════════════════════════════════════════
    # SHEET 2 — Summary Report
    # ══════════════════════════════════════════════════════════════════════════
    ws2 = wb.create_sheet("Summary Report")

    # New column order: Metric | Average Score | Pass Rate | Total
    sum_headers = ["Metric", "Average Score", "Pass Rate", "Total"]
    n_cols2     = len(sum_headers)
    start_col   = 4   # shifts the whole table right, so it sits in the middle of the sheet

    banner_row = 1
    header_row = 2
    data_start = 3

    # ── Banner ────────────────────────────────────────────────────────────────
    banner2 = ws2.cell(row=banner_row, column=start_col, value="EVALUATION SUMMARY")
    ws2.merge_cells(start_row=banner_row, start_column=start_col, end_row=banner_row, end_column=start_col + n_cols2 - 1)
    banner2.font = mk_font(bold=True, color="FFFFFF", size=12)
    banner2.fill = mk_fill(HEADER_COLOR); banner2.alignment = center; banner2.border = thin_border()
    ws2.row_dimensions[banner_row].height = 28

    # ── Column headers ───────────────────────────────────────────────────────
    for i, h in enumerate(sum_headers):
        cell = ws2.cell(row=header_row, column=start_col + i, value=h)
        cell.font = mk_font(bold=True, color="FFFFFF", size=11)
        cell.fill = mk_fill(HEADER_COLOR); cell.alignment = center; cell.border = thin_border()
    ws2.row_dimensions[header_row].height = 28

    # ── Data rows (single source of truth — one loop only) ──────────────────────
    for r_offset, rd in enumerate(summary_data):
        r = data_start + r_offset
        for i, h in enumerate(sum_headers):
            col  = start_col + i
            val  = rd[h]
            cell = ws2.cell(row=r, column=col, value=val)
            cell.border = thin_border()
            if h == "Average Score":
                cell.font = mk_font(); cell.alignment = center
                row_threshold = thresholds.get(rd["Metric"], 0.7)
                if val >= row_threshold:
                    cell.fill = mk_fill(SCORE_HIGH_COLOR)
                else:
                    cell.fill = mk_fill(fail_color_for(rd["Metric"]))
            elif h in ("Pass Rate", "Total"):
                cell.font = mk_font(); cell.alignment = center
            else:
                cell.font = mk_font(); cell.alignment = left
        ws2.row_dimensions[r].height = 28

    # Widths: Metric, Average Score, Pass Rate, Total
    for i, w in enumerate([48, 16, 22, 10]):
        ws2.column_dimensions[get_column_letter(start_col + i)].width = w

    # ── Overall pass/fail banner — sits directly under the table ────────────
    # Checks overall TEST pass rate (0-100%), not any single metric's threshold,
    # so it intentionally stays a flat 70% cutoff rather than reading `thresholds`.
    if overall_stats:
        overall_row = data_start + len(summary_data) + 1   # one blank row as a gap below the table

        overall_text = (
            f"Test Results ({overall_stats['total']} total tests)   "
            f"Pass Rate: {overall_stats['pass_rate']}%   |   "
            f"Passed: {overall_stats['passed']}   |   "
            f"Failed: {overall_stats['failed']}"
        )
        is_healthy = overall_stats['pass_rate'] >= 70
        overall_fill_color = PASS_COLOR if is_healthy else FAIL_COLOR
        overall_font_color = PASS_FONT_COLOR if is_healthy else FAIL_FONT_COLOR

        overall_cell = ws2.cell(row=overall_row, column=start_col, value=overall_text)
        ws2.merge_cells(start_row=overall_row, start_column=start_col, end_row=overall_row, end_column=start_col + n_cols2 - 1)
        overall_cell.font      = mk_font(bold=True, color=overall_font_color, size=12)
        overall_cell.fill      = mk_fill(overall_fill_color)
        overall_cell.alignment = center
        overall_cell.border    = thin_border()
        ws2.row_dimensions[overall_row].height = 30

    wb.save(output_file)
    print(f"\n📊 Report saved as {output_file}")